In [ ]:
#Use Markdown and Latex : 

In [1]:
print('hello')


hello


In [8]:
print(1 + 1)

2


In [1]:
 1.0
    

1.0

In [2]:
1 + 1

2

In [3]:
1 * 3

3

In [4]:
1 / 2

0.5

In [5]:
1/ 3

0.3333333333333333

In [6]:
2/ 4

0.5

In [7]:
2 ** 4

16

In [8]:
3 ** 5

243

In [9]:
7 % 3


1

In [10]:
"I can't put"

"I can't put"

In [11]:
num = 26
name = 'gavindu'

In [12]:
print("My age is {} and My name is {}".format(age,name))

NameError: name 'age' is not defined

In [13]:
"My age is {} and My name is {}".format(age,name)

NameError: name 'age' is not defined

In [14]:
"My age is {} and My name is {}".format(num,name)

'My age is 26 and My name is gavindu'

In [15]:
print("My age is {} and My name is {}".format(num,name))

My age is 26 and My name is gavindu


In [16]:
s = 'abcdefghijk' 

In [17]:
s[0:]

'abcdefghijk'

In [18]:
s[:3]

'abc'

In [19]:
s[:-1]

'abcdefghij'

In [20]:
s[:-4]

'abcdefg'

In [21]:
my_list = ['a', 'b', 'c']


In [22]:
my_list.append('d')

In [23]:
my_list

['a', 'b', 'c', 'd']

In [24]:
my_list[0]

'a'

In [25]:
nest = [1, 2, [3, 4]]

In [26]:
nest

[1, 2, [3, 4]]

In [27]:
nest[2]

[3, 4]

In [28]:
nest = [1, 2, 3, [4, 5,['target']]]

In [29]:
print(nest[3][2][0])

target


In [30]:
d = {'key1': 'value1', 'key2' :123}

In [31]:
d['key1']

'value1'

In [32]:
d['key2']


123

In [33]:
d = {'k1': {'innerkey':[1,2,3]}}

In [34]:
d['k1']['innerkey'][1]

2

In [35]:
 my_list = [1, 2, 3]                                  

In [36]:
my_list[0]

1

In [37]:
t= (1, 2, 3)

In [38]:
t[0]


1

In [39]:
my_list


[1, 2, 3]

In [40]:
my_list[0] = 'New'

In [41]:
my_list

['New', 2, 3]

In [42]:
t[0] = 'New'

TypeError: 'tuple' object does not support item assignment

In [43]:
s = {1, 2, 3}

In [44]:
s.add(5)

In [45]:
s


{1, 2, 3, 5}

In [46]:
s.add(5)

In [47]:
s


{1, 2, 3, 5}

In [48]:
1 > 3


False

In [49]:
4 < 7

True

In [50]:
1 < 4 and 4 < 9

True

In [51]:
2 > 4 and 5 < 8

False

In [52]:
if 1 == 2:
    print('First')
elif 4 == 4:
    print('Second')
elif 3 == 3:
    print('Middle')
else:
    print('last')
    

Second


In [55]:
i = 1
while i < 5:
    print('i is: {}'.format(i))
    i = i + 1

i is: 1
i is: 2
i is: 3
i is: 4


In [57]:
seq = [1, 2, 3, 4, 5]
for x in seq:
    print(x)

1
2
3
4
5


In [58]:
x = [1, 2, 3, 4]

In [59]:
out = []
for num in x:
    out.append(num**2)

In [60]:
print(out)

[1, 4, 9, 16]


In [61]:
[num**2 for num in x]

[1, 4, 9, 16]

In [62]:
out = [num **2 for num in x]

In [63]:
out

[1, 4, 9, 16]

In [64]:
def my_func(name= 'default name'):
    print('Hello' + name)
    

In [65]:
my_func('jose')

Hellojose


In [67]:
range()   

TypeError: range expected 1 arguments, got 0

In [68]:

map()

TypeError: map() must have at least two arguments.

In [69]:
def time2(var):
    return var*2

In [70]:
times2(5)

NameError: name 'times2' is not defined

In [71]:
time2(5)

10

#map


In [72]:
seq = [1, 2, 3, 4, 5]

In [73]:
map() 

TypeError: map() must have at least two arguments.

In [74]:
map()

TypeError: map() must have at least two arguments.

In [80]:
map()

TypeError: map() must have at least two arguments.

In [81]:
map(time2,seq)

In [82]:
list(map(time2,seq))

[2, 4, 6, 8, 10]

# lambda 


In [83]:
list(map(lambda num: num*3, seq))

[3, 6, 9, 12, 15]

In [84]:
list(filter(lambda num: num%2 == 0,seq))

[2, 4]

In [85]:
s = 'hello my is gavindu'

In [86]:
s.lower()

'hello my is gavindu'

In [87]:
s.upper()

'HELLO MY IS GAVINDU'

In [88]:
s.split()

['hello', 'my', 'is', 'gavindu']

In [89]:
tweet = 'Go sports! #Sports'

In [90]:
tweet.split('#')[1]

'Sports'

In [91]:
lst = [1, 2, 3]

In [92]:
lst.pop()

3

In [93]:
lst


[1, 2]

NumPy Array

In [94]:
my_list = [1,2,3]


In [95]:
import numpy as np

In [96]:
arr = np.array(my_list)

In [97]:
arr


array([1, 2, 3])

In [98]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [99]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [100]:
np.arrange(0,11,2)

AttributeError: module 'numpy' has no attribute 'arrange'

In [101]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [102]:
np.zeros(3)

array([0., 0., 0.])

In [103]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [104]:
np.ones(4)

array([1., 1., 1., 1.])

In [105]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [106]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [107]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [108]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [109]:
np.random.rand(5)

array([0.73747714, 0.39366306, 0.18511945, 0.34799698, 0.01598715])

In [110]:
np.random.rand(5,5)

array([[0.95248643, 0.68397206, 0.21269941, 0.08184049, 0.02112456],
       [0.85705441, 0.27596216, 0.96071741, 0.53842909, 0.38053878],
       [0.83759924, 0.85234644, 0.40779069, 0.40900219, 0.34117851],
       [0.19987186, 0.27968681, 0.32651318, 0.34874223, 0.49719965],
       [0.6216685 , 0.45811072, 0.76453044, 0.72361845, 0.24346199]])

In [111]:
np.random.randn(2)

array([-0.56575782, -0.88948149])

In [112]:
np.random.randn(4,4)

array([[ 0.27569121,  0.14380185, -0.02803352, -0.30796816],
       [ 2.23114784, -0.96116027,  0.19284115, -0.79264211],
       [ 0.49720506, -0.74064431,  0.64443542,  0.26181964],
       [-1.46710753, -0.74656729,  1.62492344, -0.596782  ]])

In [113]:
np.random.randint(1, 100, 10)

array([ 1, 56, 45, 41, 36, 25, 89, 61, 18,  7])

In [114]:
ranarr = np.random.randint(0,50,10)

In [119]:
ranarr.reshape(5,5)

ValueError: cannot reshape array of size 10 into shape (5,5)

In [120]:
arr = np.arrange(25)

AttributeError: module 'numpy' has no attribute 'arrange'

In [121]:
arr = np.arange(25)

In [122]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [123]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [124]:
arr.reshape(3,3)

ValueError: cannot reshape array of size 25 into shape (3,3)

In [125]:
arr.max()

24

In [126]:
ar.min()

NameError: name 'ar' is not defined

In [127]:
arr.min()

0

In [128]:
arr.argmax()

24

In [129]:
arr.argmin()

0

In [130]:
arr = arr.reshape(5,5)

In [131]:
arr.shape

(5, 5)

In [132]:
arr.dtype

dtype('int32')

In [133]:
from numpy.random import randint


In [134]:
randint(2,10)

6